extends: default

ignore: |
  .venv/
  output/

rules:
  document-start: disable
  empty-lines:
    max-end: 1
  indentation:
    spaces: 2
    indent-sequences: false
  line-length:
    max: 120
    allow-non-breakable-inline-mappings: true
  truthy:
    check-keys: false
